server:
  port: 8080

management:
  endpoint:
    health:
      show-details: ALWAYS
  tracing:
    enabled: true
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    mongo:
      command:
        enabled: false
    export:
      prometheus:
        enabled: true

spring:
  security:
    oauth2:
      client:
        registration:
          my-client:
            provider: my-provider
            authorization-grant-type: client_credentials
            client-id: my-client-id
            client-secret: my-client-secret
        provider:
          my-provider:
            token-uri: http://localhost:8080/oauth2/token
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver

  data:
    mongodb:
      database: test
      port: 27017

  kafka:
    embedded:
      kraft: true
    bootstrap-servers: localhost:54773
    consumer:
      auto-offset-reset: earliest
  cloud:
    function:
      definition: accountProcessor; accountConsumer; fraudConsumer
    stream:
      function.routing.enabled: true
      bindings:
        accountProcessor-in-0:
          destination: accounts-topic
          group: accountService
        accountProcessor-out-0:
          destination: processed-accounts-topic
        accountConsumer-in-0:
          destination: processed-accounts-topic
          group: internalAccountService
        fraudConsumer-in-0:
            destination: processed-accounts-topic
            group: fraudService
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest

springdoc:
  enable-spring-security: true
  show-login-endpoint: true
  show-oauth2-endpoints: true
  show-actuator: true
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

logging:
  level:
    root: INFO
    com.agilesolutions.kafka: DEBUG
    org.springframework.jpa: DEBUG
    org.springframework.mongo: DEBUG
    org.springframework.security: DEBUG

auto:
  register:
    schema: false

service:
  retry:
    initial_delay: 1000
    max-delay: 5000
    multiplier: 2.0
    max-attempts: 3



twelvedata:
  api:
    url: https://api.twelvedata.com/
    key: demo