/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.agilesolutions.kafka.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AccountAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8912735255072522782L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AccountAvro\",\"namespace\":\"com.agilesolutions.kafka.model\",\"fields\":[{\"name\":\"accountNumber\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"accountType\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"branchAddress\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AccountAvro> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AccountAvro> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AccountAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AccountAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AccountAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AccountAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AccountAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AccountAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AccountAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String accountNumber;
  private java.lang.String accountType;
  private java.lang.String branchAddress;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AccountAvro() {}

  /**
   * All-args constructor.
   * @param accountNumber The new value for accountNumber
   * @param accountType The new value for accountType
   * @param branchAddress The new value for branchAddress
   */
  public AccountAvro(java.lang.String accountNumber, java.lang.String accountType, java.lang.String branchAddress) {
    this.accountNumber = accountNumber;
    this.accountType = accountType;
    this.branchAddress = branchAddress;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return accountNumber;
    case 1: return accountType;
    case 2: return branchAddress;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: accountNumber = value$ != null ? value$.toString() : null; break;
    case 1: accountType = value$ != null ? value$.toString() : null; break;
    case 2: branchAddress = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'accountNumber' field.
   * @return The value of the 'accountNumber' field.
   */
  public java.lang.String getAccountNumber() {
    return accountNumber;
  }


  /**
   * Sets the value of the 'accountNumber' field.
   * @param value the value to set.
   */
  public void setAccountNumber(java.lang.String value) {
    this.accountNumber = value;
  }

  /**
   * Gets the value of the 'accountType' field.
   * @return The value of the 'accountType' field.
   */
  public java.lang.String getAccountType() {
    return accountType;
  }


  /**
   * Sets the value of the 'accountType' field.
   * @param value the value to set.
   */
  public void setAccountType(java.lang.String value) {
    this.accountType = value;
  }

  /**
   * Gets the value of the 'branchAddress' field.
   * @return The value of the 'branchAddress' field.
   */
  public java.lang.String getBranchAddress() {
    return branchAddress;
  }


  /**
   * Sets the value of the 'branchAddress' field.
   * @param value the value to set.
   */
  public void setBranchAddress(java.lang.String value) {
    this.branchAddress = value;
  }

  /**
   * Creates a new AccountAvro RecordBuilder.
   * @return A new AccountAvro RecordBuilder
   */
  public static com.agilesolutions.kafka.model.AccountAvro.Builder newBuilder() {
    return new com.agilesolutions.kafka.model.AccountAvro.Builder();
  }

  /**
   * Creates a new AccountAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AccountAvro RecordBuilder
   */
  public static com.agilesolutions.kafka.model.AccountAvro.Builder newBuilder(com.agilesolutions.kafka.model.AccountAvro.Builder other) {
    if (other == null) {
      return new com.agilesolutions.kafka.model.AccountAvro.Builder();
    } else {
      return new com.agilesolutions.kafka.model.AccountAvro.Builder(other);
    }
  }

  /**
   * Creates a new AccountAvro RecordBuilder by copying an existing AccountAvro instance.
   * @param other The existing instance to copy.
   * @return A new AccountAvro RecordBuilder
   */
  public static com.agilesolutions.kafka.model.AccountAvro.Builder newBuilder(com.agilesolutions.kafka.model.AccountAvro other) {
    if (other == null) {
      return new com.agilesolutions.kafka.model.AccountAvro.Builder();
    } else {
      return new com.agilesolutions.kafka.model.AccountAvro.Builder(other);
    }
  }

  /**
   * RecordBuilder for AccountAvro instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AccountAvro>
    implements org.apache.avro.data.RecordBuilder<AccountAvro> {

    private java.lang.String accountNumber;
    private java.lang.String accountType;
    private java.lang.String branchAddress;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.agilesolutions.kafka.model.AccountAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.accountNumber)) {
        this.accountNumber = data().deepCopy(fields()[0].schema(), other.accountNumber);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.accountType)) {
        this.accountType = data().deepCopy(fields()[1].schema(), other.accountType);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.branchAddress)) {
        this.branchAddress = data().deepCopy(fields()[2].schema(), other.branchAddress);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing AccountAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(com.agilesolutions.kafka.model.AccountAvro other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.accountNumber)) {
        this.accountNumber = data().deepCopy(fields()[0].schema(), other.accountNumber);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.accountType)) {
        this.accountType = data().deepCopy(fields()[1].schema(), other.accountType);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.branchAddress)) {
        this.branchAddress = data().deepCopy(fields()[2].schema(), other.branchAddress);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'accountNumber' field.
      * @return The value.
      */
    public java.lang.String getAccountNumber() {
      return accountNumber;
    }


    /**
      * Sets the value of the 'accountNumber' field.
      * @param value The value of 'accountNumber'.
      * @return This builder.
      */
    public com.agilesolutions.kafka.model.AccountAvro.Builder setAccountNumber(java.lang.String value) {
      validate(fields()[0], value);
      this.accountNumber = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'accountNumber' field has been set.
      * @return True if the 'accountNumber' field has been set, false otherwise.
      */
    public boolean hasAccountNumber() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'accountNumber' field.
      * @return This builder.
      */
    public com.agilesolutions.kafka.model.AccountAvro.Builder clearAccountNumber() {
      accountNumber = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'accountType' field.
      * @return The value.
      */
    public java.lang.String getAccountType() {
      return accountType;
    }


    /**
      * Sets the value of the 'accountType' field.
      * @param value The value of 'accountType'.
      * @return This builder.
      */
    public com.agilesolutions.kafka.model.AccountAvro.Builder setAccountType(java.lang.String value) {
      validate(fields()[1], value);
      this.accountType = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'accountType' field has been set.
      * @return True if the 'accountType' field has been set, false otherwise.
      */
    public boolean hasAccountType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'accountType' field.
      * @return This builder.
      */
    public com.agilesolutions.kafka.model.AccountAvro.Builder clearAccountType() {
      accountType = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'branchAddress' field.
      * @return The value.
      */
    public java.lang.String getBranchAddress() {
      return branchAddress;
    }


    /**
      * Sets the value of the 'branchAddress' field.
      * @param value The value of 'branchAddress'.
      * @return This builder.
      */
    public com.agilesolutions.kafka.model.AccountAvro.Builder setBranchAddress(java.lang.String value) {
      validate(fields()[2], value);
      this.branchAddress = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'branchAddress' field has been set.
      * @return True if the 'branchAddress' field has been set, false otherwise.
      */
    public boolean hasBranchAddress() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'branchAddress' field.
      * @return This builder.
      */
    public com.agilesolutions.kafka.model.AccountAvro.Builder clearBranchAddress() {
      branchAddress = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AccountAvro build() {
      try {
        AccountAvro record = new AccountAvro();
        record.accountNumber = fieldSetFlags()[0] ? this.accountNumber : (java.lang.String) defaultValue(fields()[0]);
        record.accountType = fieldSetFlags()[1] ? this.accountType : (java.lang.String) defaultValue(fields()[1]);
        record.branchAddress = fieldSetFlags()[2] ? this.branchAddress : (java.lang.String) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AccountAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<AccountAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AccountAvro>
    READER$ = (org.apache.avro.io.DatumReader<AccountAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.accountNumber);

    out.writeString(this.accountType);

    out.writeString(this.branchAddress);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.accountNumber = in.readString();

      this.accountType = in.readString();

      this.branchAddress = in.readString();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.accountNumber = in.readString();
          break;

        case 1:
          this.accountType = in.readString();
          break;

        case 2:
          this.branchAddress = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










