apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: allinone-prod
resources:
- ../../base
patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
  target:
    kind: Deployment
    name: allinone
images:
- name: allinone
  newName: agilesolutions/allinone
labels:
- includeSelectors: true
  pairs:
    env: prod
