apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
# default image (will be overridden by overlays/CI)
images:
  - name: allinone
    newTag: 0.0.1
