apiVersion: v1
kind: Service
metadata:
  name: allinone
  labels:
    app: allinone
spec:
  selector:
    app: allinone
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP  # internal-only, exposed via Ingress